### ISSUE TITLE
NER cuts away parts with no capital letter

### ISSUE THREAD

**Issue by Hveemos** [Kungbib/swedish-bert-models#5]
Hi!

First of all, great work! I wanted to try your NER-model och the parliament speeches (from https://data.riksdagen.se/). And I ran in to two issues. The number 2 is my real problem here:

1. The model only accepts text strings smaller than 511 (or 512?) tokens. which means I have to check the strings and cut them i parts before applying the function. I choose to do that by paragraphs.
2. Some entities which don't have a capital letter in the beginning is incorrectly cut into pieces.

**Example**
Input:
`text4='Utredningen från trafikutskottet kan inte betraktas som genomarbetad'`
outputs
`[{'entity': 'ORG', 'score': 0.997895359992981, 'word': '##utskottet'}]`

I made a small Colabs notebook to illustrate the problem: [Issue_NER](https://colab.research.google.com/drive/1wvexN7fsWlMfahpQ4ykaIIYujRzBLlWz)

If I instead would use a capital letter 'Trafikutskottet' it will work fine. And this problem does note apply to the ministries such as 'Arbetsmarknadsdepartementet' or 'arbetsmarknadsdepartementet'

Am I missing something or is this a failure of the model?

Regards
Joakim

**Comment by marma** [comment]
That is weird and should optimally not happen. My guess is that the score for "trafik" falls below a certain threshold and is therefore not included. This could be seen as a bug in the Transformers framework that (perhaps) should make whole words either appear or not instead of splitting them. I would suggest filing and issue.

You can, however, do this by passing `ignore_labels=[]` to the NER pipeline and piece the words together yourself.

So no, I don't think you are missing something. It could be seen as a failure of the model, on the other hand "trafikutskottet" without capitalized T is a bit confusing since that is not the actual name.

**Comment by marma** [comment]
I have updated the example with code that deals with (at least one level of) sub-words. Closing this issue. Feel free to re-open if anything did not make sense :)
